export const FETCH_CART_INIT = 'FETCH_CART_INIT'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL'

export const ADD_CART_INIT = 'ADD_CART_INIT'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAIL = 'ADD_CART_FAIL'

export const REMOVE_CART_INIT = 'REMOVE_CART_INIT'
export const REMOVE_CART_SUCCESS= 'REMOVE_CART_SUCCESS'
export const REMOVE_CART_FAIL = 'REMOVE_CART_FAIL'

export const INCREASE_Q = 'INCREASE_Q'
export const DECREASE_Q = 'DECREASE_Q'