export const FETCH_CATEGORY_INIT = 'FETCH_CATEGORY_INIT'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAIL = 'FETCH_CATEGORY_FAIL'

export const CREATE_CATEGORY_INIT = 'CREATE_CATEGORY_INIT'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const UPDATE_CATEGORY_INIT = 'UPDATE_CATEGORY_INIT'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL'

export const FETCH_ALL_CATEGORY_INIT = 'FETCH_ALL_CATEGORY_INIT'
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS'
export const FETCH_ALL_CATEGORY_FAIL = 'FETCH_ALL_CATEGORY_FAIL'